serial:
  port: '/dev/ttyUSB2'
  baudrate: 115200

at:
  commands:
    signal:
      quality: 'AT+CSQ'
    operator:
      current: 'AT+COPS?'
      list: 'AT+COPS=?'
      force:
        automatic: 'AT+COPS=0,2,'
        manual: 'AT+COPS=1,2,'
  timeout:
    small: 0.01
    regular: 0.5
    medium: 1
    big: 15

file:
  output: 'info.csv'

generation: 'higher'